### ISSUE TITLE
`sympy`, `scipy`, and `picos` dependencies are not installed with `SumOfSquares`

### ISSUE THREAD

**Issue by sdahdah** [yuanchenyang/SumOfSquares.py#8]
If I create a fresh virtual environment and run

```bash
$ pip install SumOfSquares
```

none of the dependencies are installed. If instead I clone the git repo and run

```bash
$ pip install -e ./SumOfSquares.py
```

all the dependencies are installed correctly. Does the PyPi version need to be updated?

**Comment by yuanchenyang** [comment]
Thanks for raising this issue, I've fixed it with https://github.com/yuanchenyang/SumOfSquares.py/commit/141dbd68bdf597fb8592b18c56ddae1361df9fdd
